### ISSUE TITLE
Deploying dependencies of Rook causes PersistentVolumeClaim is not bound errors

### ISSUE THREAD

**Issue by carlosedp** [luxas/kubeadm-workshop#10]
After I deploy dependencies of the Persistent Volumes, I get the following errors. The pods are in Pending state. This happens to Influx-Grafana and Prometheus:

```

[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "grafana-pv-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "grafana-pv-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "grafana-pv-claim", which is unexpected.]

---------

[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "influxdb-pv-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "influxdb-pv-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "influxdb-pv-claim", which is unexpected.]

---------

[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-sample-metrics-prom-db-prometheus-sample-metrics-prom-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-sample-metrics-prom-db-prometheus-sample-metrics-prom-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-sample-metrics-prom-db-prometheus-sample-metrics-prom-0", which is unexpected.]
```

**Comment by luxas** [comment]
Hmm, that's strange.
Will try to reproduce on a fresh cluster, hang on...

**Comment by carlosedp** [comment]
I'm actually deploying a new cluster here. Let me try it again and I report back. I found it too strange as well.

Another thing is that the secret is not called "rook-rbd-user". Rook creates it as rook-rook-user. Maybe the README needs an update.

**Comment by carlosedp** [comment]
Yep, not worked here. I've followed the pre-reqs (installed the Ceph docker image) but same error.

**Comment by luxas** [comment]
Ok, so now I've fixed it
Turned out Rook renamed their Secret from `rook-rbd-secret` to `rook-rook-secret`, updated the instructions.

Thanks for the bug report!

**Comment by carlosedp** [comment]
Even after the fix, I still got problems related to the PVC being not bound.

I fixed by adding "  storageClassName: rook-block" into the PVS "spec:" block.

**Comment by luxas** [comment]
@carlosedp Did you remember to execute this command?
```
kubectl patch storageclass rook-block -p '{"metadata":{"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
```

**Comment by carlosedp** [comment]
@luxas Yes, I did. I have redeployed Rook and wanted to test this.
