### ISSUE TITLE
Add short explanation why special hyperkube image is required

### ISSUE THREAD

**Issue by rhuss** [luxas/kubeadm-workshop#2]
From the workshop document:

>  KUBE_HYPERKUBE_IMAGE=luxas/hyperkube:v1.6.0-kubeadm-workshop-2 kubeadm init --config kubeadm.yaml

Just curious why a special hyperkube is required and how does it differ from the plain hyperkube. Would be awesome if one or two sentences could be added explaining the difference. (I'm asking because I'm currently on the way to update https://github.com/Project31/ansible-kubernetes-openshift-pi3 for the latest kubeadm awesomeness ;-)

**Comment by rhuss** [comment]
Sorry, didn't read to the end of the README where it is explained.


Sorry for the noise ...

**Comment by luxas** [comment]
Noise here is good, it's pretty quiet anyway ;)

I've fixed this now, it should be higher up in the doc, where you expected to read about it/see it.
I'm excited that you're using this guide, feel free to open new issues when (not if) you find more issues with it or want more improvements

**Comment by luxas** [comment]
Now I was able to remove the custom hyperkube dep, yayy!

**Comment by rhuss** [comment]
awesome ;-) have to pick up the thread again. unfortunately, I can only work in batches now and then on my pi cluster ;-(. Is rook finally working on arm32 ? I'm considering, for now, to move to plain NFS for PVs (boring, I know ....) until a real cluster FS is working without too much tweaking.

**Comment by luxas** [comment]
Rook isn't working on arm32 yet unfortunately due to some SIGILLs between C++ and Go. More info linked from this thread: https://github.com/rook/rook/pull/497
