### ISSUE TITLE
Can I get the source code of images：luxas/autoscale-demo:v0.1.2

### ISSUE THREAD

**Issue by Alivers** [luxas/kubeadm-workshop#49]
In kubeadm-workshop/demos/monitoring/sample-metrics-app.yaml, the images for deployment sample-metrics-app deploying for.
I'm writing my own custom metrics API server. I had deployed the sample-metrics-app in my cluster and its custom metrics(http_requests) worked, so I want to figure out how to implement it.  Can I get the source code of images：luxas/autoscale-demo:v0.1.2 ? Thanks!

**Comment by dnzprmksz** [comment]
Hey @Alivers I guess you were looking for the file below. I was searching for the same. So I hope this will help other people who end up here :v:
https://github.com/luxas/kubeadm-workshop/blob/master/images/autoscaling/server.js

**Comment by Alivers** [comment]
> Hey @Alivers I guess you were looking for the file below. I was searching for the same. So I hope this will help other people who end up here ✌️ https://github.com/luxas/kubeadm-workshop/blob/master/images/autoscaling/server.js

Exactly! Thanks for your reply.
