### ISSUE TITLE
Reboot support planned ?

### ISSUE THREAD

**Issue by rhuss** [luxas/kubeadm-workshop#5]
Any thoughts how to solve the problem with rebooting a k8s cluster as stated in the "Known Issues section" (see #4)  ? would be awesome if we could get this resolved as I expected that a pi cluster will be carried around a lot (e.g. to conferences ;-), so rebooting / restarting will happen quite often. Reinstalling the cluster afresh always before a demo is not really an option.

**Comment by luxas** [comment]
Reboot support planned for self-hosting in v1.7, but if you want that now, you have to go with non-selfhosting (and then currently no API aggregation)

I'll improve this as more of the API aggregation code is merged to master and kubeadm v1.6.x stabilizes

**Comment by rhuss** [comment]
Thanks for the info, will stick to non self-hosted mode for now. But will come back to it later, for sure :)

**Comment by luxas** [comment]
Now it's possible to use API aggregation in non-self hosted mode so you can do even cooler demos on your conferences ;)
