### ISSUE TITLE
Problems with kubeadm init with 1.6.0

### ISSUE THREAD

**Issue by rhuss** [luxas/kubeadm-workshop#6]
Because of https://github.com/kubernetes/kubeadm/issues/212 the init of the master fails.

Seems like an hen-and-egg issue: `kubeadm` waits for an cni plugin to be installed until the first node is considered to be running, but the cni plugin (weave) is only installed after `kubeadm init`.

**Comment by rhuss** [comment]
Fixed with kubeadm 1.6.1 (still have issues with weave though :)

**Comment by luxas** [comment]
Yep, focused on getting v1.6.1 out and fixing the issue for kubeadm officially first before fixing my own project ;) will switch to kubeadm stable channel soon
