### ISSUE TITLE
sample-apiserver failed to start

### ISSUE THREAD

**Issue by portis24** [luxas/kubeadm-workshop#9]
$ kubectl -n wardle logs wardle-apiserver-2109496523-s604f wardle-server

...
panic: unknown flag: --etcd-servers

goroutine 1 [running]:
panic(0x13efce0, 0xc4204452c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/go/src/k8s.io/custom-metrics-boilerplate/sample-main.go:40 +0x126

**Comment by luxas** [comment]
Thanks @portis24 for the bug report!
I don't know how that happened really, probably a bad docker image push to the Docker Hub made by me.

However, now fixed ;)
